export const plans = {
  en: [
    {
      icon: 'iconsminds-male',
      title: 'DEVELOPER',
      price: '$11',
      detail: 'User/Month',
      link: '#',
      features: ['Number of end products 1', 'Free updates', 'Forum support'],
    },
    {
      icon: 'iconsminds-male-female',
      title: 'TEAM',
      price: '$17',
      detail: 'User/Month Up to 10 Users',
      link: '#',
      features: [
        '24/5 support',
        'Number of end products 1',
        'Two factor authentication',
        'Free updates',
        'Forum support',
      ],
    },
    {
      icon: 'iconsminds-mens',
      title: 'ENTERPRISE',
      price: '$19',
      detail: 'User/Month 10+ Users',
      link: '#',
      features: [
        '24/7 support',
        'Number of end products 1',
        'Two factor authentication',
        'Free updates',
        'Forum support',
      ],
    },
  ],
  da: [
    {
      num_id: 1,
      id: 'Starter',
      icon: 'iconsminds-plane',
      title: 'STARTER',
      price: 'GRATIS*',
      price_mdr: '*STARTER planen er for dig der gerne vil teste platformen af. Når du vælger STARTER så har du 7 dage uden binding, og dette koster dig 0 kr. For det får du 3 bud helt uden forpligtelser i de 7 dage. Du kan til enhver tid opsige "STARTER"-planen, dog inden for de 7 dage planen løber. Såfremt du ikke opsiger "STARTER"-planen rettidigt, så vil vi pr. automatik opgradere din "STARTER"-plan til en "LITE"-plan. Denne plan koster 795 kr. / mdr. ekskl. moms. Du binder dig samtidig i 6 mdr. til planen jf. vores almindelige forretningsbetingelser. De 7 dages fri opsigelse på "STARTER"-planen tager ikke forbehold for weekender og helligdage, og tæller opstartsdatoen inklusive. Det er kun muligt at oprette, samt at have, en "STARTER"-plan pr. person/virksomhed.',
      price_color: 'color-orange',
      detail: '',
      features: [
        { left: 'Bud', right: '3', is_mdr: true },
        { left: 'Superbud', right: '0', is_mdr: true },
        { left: 'Binding', right: 'Ingen', is_mdr: true },
        { left: 'Online support', right: 'Nej', is_mdr: false },
      ],
    },
    {
      num_id: 2,
      id: 'Lite',
      icon: 'iconsminds-dollar-sign-2',
      title: 'LITE',
      price: '795',
      price_mdr: '795',
      price_color: 'color-gray',
      detail: 'pr. mdr',
      features: [
        { left: 'Bud', right: '10', is_mdr: true },
        { left: 'Superbud', right: '0', is_mdr: true },
        { left: 'Binding', right: '6', is_mdr: true },
        { left: 'Online support', right: 'Nej', is_mdr: false },
      ],
    },
    {
      num_id: 3,
      id: 'Gold',
      icon: 'iconsminds-gift-box',
      title: 'GOLD',
      price: '2.995',
      price_mdr: '2.995',
      price_color: 'color-gray',
      detail: 'pr. mdr.',
      features: [
        { left: 'Bud', right: '999', is_mdr: true },
        { left: 'Superbud', right: '3', is_mdr: true },
        { left: 'Binding', right: '6', is_mdr: true },
        { left: 'Online support', right: 'Ja', is_mdr: false },
      ],
    },
  ],
};
export default plans;
